<?php

namespace Database\Seeders;

use App\Models\FishingGear;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Class FishingGearIsscfgCanonicalSeeder
 *
 * CANONICAL MASTER DATA SEEDER - FAO/CWP ISSCFG Rev.1 (2016 / CWP-25)
 * Sumber Resmi: FAO CWP Annex M (AnnexM2fishinggear.pdf) & FAO Technical Paper 672.
 *
 * Fitur Keamanan & Kepatuhan:
 * 1. Murni Idempoten (aman dijalankan berulang kali).
 * 2. Menjaga ID 1–12 data lokal Aceh operasional secara mutlak.
 * 3. Mengoreksi in-place mismatch 03.14 (OTP) dan 03.15 (PTB).
 * 4. Meng-upgrade in-place kode legacy 20.0 menjadi standar canonical 99.9 (NK) pada ID 23.
 * 5. Menambahkan 18 missing records resmi FAO/CWP Annex M Rev.1.
 * 6. Menggunakan resolusi hierarki multi-pass (Level 1 -> Level 2 -> Level 3 -> Local).
 * 7. Dibungkus dalam DB::transaction() penuh (auto-rollback jika error).
 */
class FishingGearIsscfgCanonicalSeeder extends Seeder
{
    public function run(): void
    {
        DB::transaction(function () {
            // 0. Penanganan upgrade aman untuk kode 20.0 -> 99.9
            $legacy20 = FishingGear::where('code', 'FAO-20.0')
                ->orWhere('isscfg_code', '20.0')
                ->first();

            if ($legacy20) {
                $legacy20->update([
                    'code' => 'FAO-99.9',
                    'isscfg_code' => '99.9',
                    'standard_abbreviation' => 'NK',
                    'name' => 'Gear not known (Alat tangkap tidak diketahui)',
                    'name_en' => 'Gear not known',
                    'name_id' => 'Alat tangkap tidak diketahui',
                    'category' => 'lainnya',
                    'level' => 1,
                    'parent_id' => null,
                ]);
            }

            // 1. DAFTAR CANONICAL FAO/CWP ISSCFG ANNEX M REV. 1 (2016) - 76 RECORDS
            $canonicalFaoGears = [
                // === 01 SURROUNDING NETS ===
                [
                    'isscfg_code' => '01.0',
                    'standard_abbreviation' => null,
                    'name_en' => 'Surrounding nets',
                    'name_id' => 'Jaring lingkar / pukat cincin',
                    'category' => 'jaring_lingkar',
                    'level' => 1,
                    'parent_code' => null,
                    'sort_order' => 10,
                ],
                [
                    'isscfg_code' => '01.1',
                    'standard_abbreviation' => 'PS',
                    'name_en' => 'Purse seines',
                    'name_id' => 'Pukat cincin',
                    'category' => 'jaring_lingkar',
                    'level' => 2,
                    'parent_code' => '01.0',
                    'sort_order' => 11,
                ],
                [
                    'isscfg_code' => '01.2',
                    'standard_abbreviation' => 'LA',
                    'name_en' => 'Surrounding nets without purse lines',
                    'name_id' => 'Jaring lingkar tanpa tali kolor (lampara)',
                    'category' => 'jaring_lingkar',
                    'level' => 2,
                    'parent_code' => '01.0',
                    'sort_order' => 12,
                ],
                [
                    'isscfg_code' => '01.9',
                    'standard_abbreviation' => 'SUX',
                    'name_en' => 'Surrounding nets (nei)',
                    'name_id' => 'Jaring lingkar lainnya (nei)',
                    'category' => 'jaring_lingkar',
                    'level' => 2,
                    'parent_code' => '01.0',
                    'sort_order' => 19,
                ],

                // === 02 SEINE NETS ===
                [
                    'isscfg_code' => '02.0',
                    'standard_abbreviation' => null,
                    'name_en' => 'Seine nets',
                    'name_id' => 'Pukat tarik',
                    'category' => 'jaring_tarik',
                    'level' => 1,
                    'parent_code' => null,
                    'sort_order' => 20,
                ],
                [
                    'isscfg_code' => '02.1',
                    'standard_abbreviation' => 'SB',
                    'name_en' => 'Beach seines',
                    'name_id' => 'Pukat pantai',
                    'category' => 'jaring_tarik',
                    'level' => 2,
                    'parent_code' => '02.0',
                    'sort_order' => 21,
                ],
                [
                    'isscfg_code' => '02.2',
                    'standard_abbreviation' => 'SV',
                    'name_en' => 'Boat seines',
                    'name_id' => 'Pukat tarik kapal',
                    'category' => 'jaring_tarik',
                    'level' => 2,
                    'parent_code' => '02.0',
                    'sort_order' => 22,
                ],
                [
                    'isscfg_code' => '02.21',
                    'standard_abbreviation' => 'SDN',
                    'name_en' => 'Danish seines',
                    'name_id' => 'Pukat tarik Denmark',
                    'category' => 'jaring_tarik',
                    'level' => 3,
                    'parent_code' => '02.2',
                    'sort_order' => 23,
                ],
                [
                    'isscfg_code' => '02.22',
                    'standard_abbreviation' => 'SSC',
                    'name_en' => 'Scottish seines',
                    'name_id' => 'Pukat tarik Skotlandia',
                    'category' => 'jaring_tarik',
                    'level' => 3,
                    'parent_code' => '02.2',
                    'sort_order' => 24,
                ],
                [
                    'isscfg_code' => '02.23',
                    'standard_abbreviation' => 'SPR',
                    'name_en' => 'Pair seines',
                    'name_id' => 'Pukat tarik berpasangan',
                    'category' => 'jaring_tarik',
                    'level' => 3,
                    'parent_code' => '02.2',
                    'sort_order' => 25,
                ],
                [
                    'isscfg_code' => '02.9',
                    'standard_abbreviation' => 'SX',
                    'name_en' => 'Seine nets (nei)',
                    'name_id' => 'Pukat tarik lainnya (nei)',
                    'category' => 'jaring_tarik',
                    'level' => 2,
                    'parent_code' => '02.0',
                    'sort_order' => 29,
                ],

                // === 03 TRAWLS ===
                [
                    'isscfg_code' => '03.0',
                    'standard_abbreviation' => null,
                    'name_en' => 'Trawls',
                    'name_id' => 'Pukat hela',
                    'category' => 'jaring_hela',
                    'level' => 1,
                    'parent_code' => null,
                    'sort_order' => 30,
                ],
                [
                    'isscfg_code' => '03.1',
                    'standard_abbreviation' => null,
                    'name_en' => 'Bottom trawls',
                    'name_id' => 'Pukat hela dasar',
                    'category' => 'jaring_hela',
                    'level' => 2,
                    'parent_code' => '03.0',
                    'sort_order' => 31,
                ],
                [
                    'isscfg_code' => '03.11',
                    'standard_abbreviation' => 'TBB',
                    'name_en' => 'Beam trawls',
                    'name_id' => 'Pukat hela berpalang dasar',
                    'category' => 'jaring_hela',
                    'level' => 3,
                    'parent_code' => '03.1',
                    'sort_order' => 32,
                ],
                [
                    'isscfg_code' => '03.12',
                    'standard_abbreviation' => 'OTB',
                    'name_en' => 'Single boat bottom otter trawls',
                    'name_id' => 'Pukat hela berpapan dasar tunggal',
                    'category' => 'jaring_hela',
                    'level' => 3,
                    'parent_code' => '03.1',
                    'sort_order' => 33,
                ],
                [
                    'isscfg_code' => '03.13',
                    'standard_abbreviation' => 'OTT',
                    'name_en' => 'Twin bottom otter trawls',
                    'name_id' => 'Pukat hela berpapan dasar ganda dua',
                    'category' => 'jaring_hela',
                    'level' => 3,
                    'parent_code' => '03.1',
                    'sort_order' => 34,
                ],
                [
                    'isscfg_code' => '03.14',
                    'standard_abbreviation' => 'OTP',
                    'name_en' => 'Multiple bottom otter trawls',
                    'name_id' => 'Pukat hela berpapan dasar ganda banyak',
                    'category' => 'jaring_hela',
                    'level' => 3,
                    'parent_code' => '03.1',
                    'sort_order' => 35,
                ],
                [
                    'isscfg_code' => '03.15',
                    'standard_abbreviation' => 'PTB',
                    'name_en' => 'Bottom pair trawls',
                    'name_id' => 'Pukat hela pasangan dasar',
                    'category' => 'jaring_hela',
                    'level' => 3,
                    'parent_code' => '03.1',
                    'sort_order' => 36,
                ],
                [
                    'isscfg_code' => '03.19',
                    'standard_abbreviation' => 'TB',
                    'name_en' => 'Bottom trawls (nei)',
                    'name_id' => 'Pukat hela dasar lainnya (nei)',
                    'category' => 'jaring_hela',
                    'level' => 3,
                    'parent_code' => '03.1',
                    'sort_order' => 37,
                ],
                [
                    'isscfg_code' => '03.2',
                    'standard_abbreviation' => null,
                    'name_en' => 'Midwater trawls',
                    'name_id' => 'Pukat hela pertengahan',
                    'category' => 'jaring_hela',
                    'level' => 2,
                    'parent_code' => '03.0',
                    'sort_order' => 38,
                ],
                [
                    'isscfg_code' => '03.21',
                    'standard_abbreviation' => 'OTM',
                    'name_en' => 'Single boat midwater otter trawls',
                    'name_id' => 'Pukat hela berpapan pertengahan tunggal',
                    'category' => 'jaring_hela',
                    'level' => 3,
                    'parent_code' => '03.2',
                    'sort_order' => 39,
                ],
                [
                    'isscfg_code' => '03.22',
                    'standard_abbreviation' => 'PTM',
                    'name_en' => 'Midwater pair trawls',
                    'name_id' => 'Pukat hela pasangan pertengahan',
                    'category' => 'jaring_hela',
                    'level' => 3,
                    'parent_code' => '03.2',
                    'sort_order' => 40,
                ],
                [
                    'isscfg_code' => '03.29',
                    'standard_abbreviation' => 'TM',
                    'name_en' => 'Midwater trawls (nei)',
                    'name_id' => 'Pukat hela pertengahan lainnya (nei)',
                    'category' => 'jaring_hela',
                    'level' => 3,
                    'parent_code' => '03.2',
                    'sort_order' => 41,
                ],
                [
                    'isscfg_code' => '03.3',
                    'standard_abbreviation' => 'TSP',
                    'name_en' => 'Semipelagic trawls',
                    'name_id' => 'Pukat hela semipelagis',
                    'category' => 'jaring_hela',
                    'level' => 2,
                    'parent_code' => '03.0',
                    'sort_order' => 42,
                ],
                [
                    'isscfg_code' => '03.9',
                    'standard_abbreviation' => 'TX',
                    'name_en' => 'Trawls (nei)',
                    'name_id' => 'Pukat hela lainnya (nei)',
                    'category' => 'jaring_hela',
                    'level' => 2,
                    'parent_code' => '03.0',
                    'sort_order' => 43,
                ],

                // === 04 DREDGES ===
                [
                    'isscfg_code' => '04.0',
                    'standard_abbreviation' => null,
                    'name_en' => 'Dredges',
                    'name_id' => 'Penggaruk',
                    'category' => 'lainnya',
                    'level' => 1,
                    'parent_code' => null,
                    'sort_order' => 50,
                ],
                [
                    'isscfg_code' => '04.1',
                    'standard_abbreviation' => 'DRB',
                    'name_en' => 'Towed dredges',
                    'name_id' => 'Penggaruk tarik kapal',
                    'category' => 'lainnya',
                    'level' => 2,
                    'parent_code' => '04.0',
                    'sort_order' => 51,
                ],
                [
                    'isscfg_code' => '04.2',
                    'standard_abbreviation' => 'DRH',
                    'name_en' => 'Hand dredges',
                    'name_id' => 'Penggaruk tangan',
                    'category' => 'lainnya',
                    'level' => 2,
                    'parent_code' => '04.0',
                    'sort_order' => 52,
                ],
                [
                    'isscfg_code' => '04.3',
                    'standard_abbreviation' => 'DRM',
                    'name_en' => 'Mechanized dredges',
                    'name_id' => 'Penggaruk mekanis',
                    'category' => 'lainnya',
                    'level' => 2,
                    'parent_code' => '04.0',
                    'sort_order' => 53,
                ],
                [
                    'isscfg_code' => '04.9',
                    'standard_abbreviation' => 'DRX',
                    'name_en' => 'Dredges (nei)',
                    'name_id' => 'Penggaruk lainnya (nei)',
                    'category' => 'lainnya',
                    'level' => 2,
                    'parent_code' => '04.0',
                    'sort_order' => 59,
                ],

                // === 05 LIFT NETS ===
                [
                    'isscfg_code' => '05.0',
                    'standard_abbreviation' => null,
                    'name_en' => 'Lift nets',
                    'name_id' => 'Jaring angkat',
                    'category' => 'jaring_angkat',
                    'level' => 1,
                    'parent_code' => null,
                    'sort_order' => 60,
                ],
                [
                    'isscfg_code' => '05.1',
                    'standard_abbreviation' => 'LNP',
                    'name_en' => 'Portable lift nets',
                    'name_id' => 'Jaring angkat portabel / anco',
                    'category' => 'jaring_angkat',
                    'level' => 2,
                    'parent_code' => '05.0',
                    'sort_order' => 61,
                ],
                [
                    'isscfg_code' => '05.2',
                    'standard_abbreviation' => 'LNB',
                    'name_en' => 'Boat-operated lift nets',
                    'name_id' => 'Jaring angkat kapal (bagan perahu)',
                    'category' => 'jaring_angkat',
                    'level' => 2,
                    'parent_code' => '05.0',
                    'sort_order' => 62,
                ],
                [
                    'isscfg_code' => '05.3',
                    'standard_abbreviation' => 'LNS',
                    'name_en' => 'Shore-operated stationary lift nets',
                    'name_id' => 'Jaring angkat menetap pantai (bagan tancap)',
                    'category' => 'jaring_angkat',
                    'level' => 2,
                    'parent_code' => '05.0',
                    'sort_order' => 63,
                ],
                [
                    'isscfg_code' => '05.9',
                    'standard_abbreviation' => 'LN',
                    'name_en' => 'Lift nets (nei)',
                    'name_id' => 'Jaring angkat lainnya (nei)',
                    'category' => 'jaring_angkat',
                    'level' => 2,
                    'parent_code' => '05.0',
                    'sort_order' => 69,
                ],

                // === 06 FALLING GEAR ===
                [
                    'isscfg_code' => '06.0',
                    'standard_abbreviation' => null,
                    'name_en' => 'Falling gear',
                    'name_id' => 'Alat yang dijatuhkan',
                    'category' => 'alat_jatuh',
                    'level' => 1,
                    'parent_code' => null,
                    'sort_order' => 70,
                ],
                [
                    'isscfg_code' => '06.1',
                    'standard_abbreviation' => 'FCN',
                    'name_en' => 'Cast nets',
                    'name_id' => 'Jala lempar',
                    'category' => 'alat_jatuh',
                    'level' => 2,
                    'parent_code' => '06.0',
                    'sort_order' => 71,
                ],
                [
                    'isscfg_code' => '06.2',
                    'standard_abbreviation' => 'FCO',
                    'name_en' => 'Cover pots/Lantern nets',
                    'name_id' => 'Perangkap penutup / tangguk lentera',
                    'category' => 'alat_jatuh',
                    'level' => 2,
                    'parent_code' => '06.0',
                    'sort_order' => 72,
                ],
                [
                    'isscfg_code' => '06.9',
                    'standard_abbreviation' => 'FG',
                    'name_en' => 'Falling gear (nei)',
                    'name_id' => 'Alat jatuh lainnya (nei)',
                    'category' => 'alat_jatuh',
                    'level' => 2,
                    'parent_code' => '06.0',
                    'sort_order' => 79,
                ],

                // === 07 GILLNETS AND ENTANGLING NETS ===
                [
                    'isscfg_code' => '07.0',
                    'standard_abbreviation' => null,
                    'name_en' => 'Gillnets and entangling nets',
                    'name_id' => 'Jaring insang dan jaring puntal',
                    'category' => 'jaring_insang',
                    'level' => 1,
                    'parent_code' => null,
                    'sort_order' => 80,
                ],
                [
                    'isscfg_code' => '07.1',
                    'standard_abbreviation' => 'GNS',
                    'name_en' => 'Set gillnets (anchored)',
                    'name_id' => 'Jaring insang tetap (berjangkar)',
                    'category' => 'jaring_insang',
                    'level' => 2,
                    'parent_code' => '07.0',
                    'sort_order' => 81,
                ],
                [
                    'isscfg_code' => '07.2',
                    'standard_abbreviation' => 'GND',
                    'name_en' => 'Drift gillnets',
                    'name_id' => 'Jaring insang hanyut',
                    'category' => 'jaring_insang',
                    'level' => 2,
                    'parent_code' => '07.0',
                    'sort_order' => 82,
                ],
                [
                    'isscfg_code' => '07.3',
                    'standard_abbreviation' => 'GNC',
                    'name_en' => 'Encircling gillnets',
                    'name_id' => 'Jaring insang lingkar',
                    'category' => 'jaring_insang',
                    'level' => 2,
                    'parent_code' => '07.0',
                    'sort_order' => 83,
                ],
                [
                    'isscfg_code' => '07.4',
                    'standard_abbreviation' => 'GNF',
                    'name_en' => 'Fixed gillnets (on stakes)',
                    'name_id' => 'Jaring insang pancang',
                    'category' => 'jaring_insang',
                    'level' => 2,
                    'parent_code' => '07.0',
                    'sort_order' => 84,
                ],
                [
                    'isscfg_code' => '07.5',
                    'standard_abbreviation' => 'GTR',
                    'name_en' => 'Trammel nets',
                    'name_id' => 'Jaring tiga lapis / jaring puntal (trammel net)',
                    'category' => 'jaring_insang',
                    'level' => 2,
                    'parent_code' => '07.0',
                    'sort_order' => 85,
                ],
                [
                    'isscfg_code' => '07.6',
                    'standard_abbreviation' => 'GTN',
                    'name_en' => 'Combined gillnets-trammel nets',
                    'name_id' => 'Kombinasi jaring insang dan puntal',
                    'category' => 'jaring_insang',
                    'level' => 2,
                    'parent_code' => '07.0',
                    'sort_order' => 86,
                ],
                [
                    'isscfg_code' => '07.9',
                    'standard_abbreviation' => 'GEN',
                    'name_en' => 'Gillnets and entangling nets (nei)',
                    'name_id' => 'Jaring insang dan puntal lainnya (nei)',
                    'category' => 'jaring_insang',
                    'level' => 2,
                    'parent_code' => '07.0',
                    'sort_order' => 89,
                ],

                // === 08 TRAPS ===
                [
                    'isscfg_code' => '08.0',
                    'standard_abbreviation' => null,
                    'name_en' => 'Traps',
                    'name_id' => 'Perangkap',
                    'category' => 'perangkap',
                    'level' => 1,
                    'parent_code' => null,
                    'sort_order' => 90,
                ],
                [
                    'isscfg_code' => '08.1',
                    'standard_abbreviation' => 'FPN',
                    'name_en' => 'Stationary uncovered pound nets',
                    'name_id' => 'Perangkap tebar terbuka menetap',
                    'category' => 'perangkap',
                    'level' => 2,
                    'parent_code' => '08.0',
                    'sort_order' => 91,
                ],
                [
                    'isscfg_code' => '08.2',
                    'standard_abbreviation' => 'FPO',
                    'name_en' => 'Pots',
                    'name_id' => 'Bubu / perangkap bertutup',
                    'category' => 'perangkap',
                    'level' => 2,
                    'parent_code' => '08.0',
                    'sort_order' => 92,
                ],
                [
                    'isscfg_code' => '08.3',
                    'standard_abbreviation' => 'FYK',
                    'name_en' => 'Fyke nets',
                    'name_id' => 'Jaring corong (fyke net)',
                    'category' => 'perangkap',
                    'level' => 2,
                    'parent_code' => '08.0',
                    'sort_order' => 93,
                ],
                [
                    'isscfg_code' => '08.4',
                    'standard_abbreviation' => 'FSN',
                    'name_en' => 'Stow nets',
                    'name_id' => 'Jaring kantong arus (jermal/stow net)',
                    'category' => 'perangkap',
                    'level' => 2,
                    'parent_code' => '08.0',
                    'sort_order' => 94,
                ],
                [
                    'isscfg_code' => '08.5',
                    'standard_abbreviation' => 'FWR',
                    'name_en' => 'Barriers, fences, weirs, etc.',
                    'name_id' => 'Sero, pagar perangkap, bendung, dll.',
                    'category' => 'perangkap',
                    'level' => 2,
                    'parent_code' => '08.0',
                    'sort_order' => 95,
                ],
                [
                    'isscfg_code' => '08.6',
                    'standard_abbreviation' => 'FAR',
                    'name_en' => 'Aerial traps',
                    'name_id' => 'Perangkap udara (ikan terbang)',
                    'category' => 'perangkap',
                    'level' => 2,
                    'parent_code' => '08.0',
                    'sort_order' => 96,
                ],
                [
                    'isscfg_code' => '08.9',
                    'standard_abbreviation' => 'FIX',
                    'name_en' => 'Traps (nei)',
                    'name_id' => 'Perangkap lainnya (nei)',
                    'category' => 'perangkap',
                    'level' => 2,
                    'parent_code' => '08.0',
                    'sort_order' => 99,
                ],

                // === 09 HOOKS AND LINES ===
                [
                    'isscfg_code' => '09.0',
                    'standard_abbreviation' => null,
                    'name_en' => 'Hooks and lines',
                    'name_id' => 'Pancing',
                    'category' => 'pancing',
                    'level' => 1,
                    'parent_code' => null,
                    'sort_order' => 100,
                ],
                [
                    'isscfg_code' => '09.1',
                    'standard_abbreviation' => 'LHP',
                    'name_en' => 'Handlines and hand-operated pole-and-lines',
                    'name_id' => 'Pancing ulur dan pancing gandar tangan',
                    'category' => 'pancing',
                    'level' => 2,
                    'parent_code' => '09.0',
                    'sort_order' => 101,
                ],
                [
                    'isscfg_code' => '09.2',
                    'standard_abbreviation' => 'LHM',
                    'name_en' => 'Mechanized lines and pole-and-lines',
                    'name_id' => 'Pancing mekanis / pancing gelendong mekanis',
                    'category' => 'pancing',
                    'level' => 2,
                    'parent_code' => '09.0',
                    'sort_order' => 102,
                ],
                [
                    'isscfg_code' => '09.3',
                    'standard_abbreviation' => null,
                    'name_en' => 'Longlines',
                    'name_id' => 'Rawai',
                    'category' => 'pancing',
                    'level' => 2,
                    'parent_code' => '09.0',
                    'sort_order' => 103,
                ],
                [
                    'isscfg_code' => '09.31',
                    'standard_abbreviation' => 'LLS',
                    'name_en' => 'Set longlines',
                    'name_id' => 'Rawai dasar (tetap)',
                    'category' => 'pancing',
                    'level' => 3,
                    'parent_code' => '09.3',
                    'sort_order' => 104,
                ],
                [
                    'isscfg_code' => '09.32',
                    'standard_abbreviation' => 'LLD',
                    'name_en' => 'Drifting longlines',
                    'name_id' => 'Rawai hanyut (rawai tuna)',
                    'category' => 'pancing',
                    'level' => 3,
                    'parent_code' => '09.3',
                    'sort_order' => 105,
                ],
                [
                    'isscfg_code' => '09.39',
                    'standard_abbreviation' => 'LL',
                    'name_en' => 'Longlines (nei)',
                    'name_id' => 'Rawai lainnya (nei)',
                    'category' => 'pancing',
                    'level' => 3,
                    'parent_code' => '09.3',
                    'sort_order' => 106,
                ],
                [
                    'isscfg_code' => '09.4',
                    'standard_abbreviation' => 'LVT',
                    'name_en' => 'Vertical lines',
                    'name_id' => 'Pancing vertikal',
                    'category' => 'pancing',
                    'level' => 2,
                    'parent_code' => '09.0',
                    'sort_order' => 107,
                ],
                [
                    'isscfg_code' => '09.5',
                    'standard_abbreviation' => 'LTL',
                    'name_en' => 'Trolling lines',
                    'name_id' => 'Pancing tonda',
                    'category' => 'pancing',
                    'level' => 2,
                    'parent_code' => '09.0',
                    'sort_order' => 108,
                ],
                [
                    'isscfg_code' => '09.9',
                    'standard_abbreviation' => 'LX',
                    'name_en' => 'Hooks and lines (nei)',
                    'name_id' => 'Pancing lainnya (nei)',
                    'category' => 'pancing',
                    'level' => 2,
                    'parent_code' => '09.0',
                    'sort_order' => 109,
                ],

                // === 10 MISCELLANEOUS GEAR ===
                [
                    'isscfg_code' => '10.0',
                    'standard_abbreviation' => null,
                    'name_en' => 'Miscellaneous gear',
                    'name_id' => 'Alat tangkap lainnya',
                    'category' => 'alat_penjepit_melukai',
                    'level' => 1,
                    'parent_code' => null,
                    'sort_order' => 110,
                ],
                [
                    'isscfg_code' => '10.1',
                    'standard_abbreviation' => 'HAR',
                    'name_en' => 'Harpoons',
                    'name_id' => 'Harpon / tombak',
                    'category' => 'alat_penjepit_melukai',
                    'level' => 2,
                    'parent_code' => '10.0',
                    'sort_order' => 111,
                ],
                [
                    'isscfg_code' => '10.2',
                    'standard_abbreviation' => 'MHI',
                    'name_en' => 'Hand implements',
                    'name_id' => 'Peralatan tangan',
                    'category' => 'alat_penjepit_melukai',
                    'level' => 2,
                    'parent_code' => '10.0',
                    'sort_order' => 112,
                ],
                [
                    'isscfg_code' => '10.3',
                    'standard_abbreviation' => 'MPM',
                    'name_en' => 'Pumps',
                    'name_id' => 'Pompa penangkap ikan',
                    'category' => 'lainnya',
                    'level' => 2,
                    'parent_code' => '10.0',
                    'sort_order' => 113,
                ],
                [
                    'isscfg_code' => '10.4',
                    'standard_abbreviation' => 'MEL',
                    'name_en' => 'Electric fishing',
                    'name_id' => 'Penangkapan ikan listrik',
                    'category' => 'lainnya',
                    'level' => 2,
                    'parent_code' => '10.0',
                    'sort_order' => 114,
                ],
                [
                    'isscfg_code' => '10.5',
                    'standard_abbreviation' => 'MPN',
                    'name_en' => 'Pushnets',
                    'name_id' => 'Jaring dorong (sondong)',
                    'category' => 'lainnya',
                    'level' => 2,
                    'parent_code' => '10.0',
                    'sort_order' => 115,
                ],
                [
                    'isscfg_code' => '10.6',
                    'standard_abbreviation' => 'MSP',
                    'name_en' => 'Scoopnets',
                    'name_id' => 'Tangguk / seser',
                    'category' => 'lainnya',
                    'level' => 2,
                    'parent_code' => '10.0',
                    'sort_order' => 116,
                ],
                [
                    'isscfg_code' => '10.7',
                    'standard_abbreviation' => 'MDR',
                    'name_en' => 'Drive-in nets',
                    'name_id' => 'Jaring halau (muroami)',
                    'category' => 'lainnya',
                    'level' => 2,
                    'parent_code' => '10.0',
                    'sort_order' => 117,
                ],
                [
                    'isscfg_code' => '10.8',
                    'standard_abbreviation' => 'MDV',
                    'name_en' => 'Diving',
                    'name_id' => 'Penyelaman',
                    'category' => 'lainnya',
                    'level' => 2,
                    'parent_code' => '10.0',
                    'sort_order' => 118,
                ],
                [
                    'isscfg_code' => '10.9',
                    'standard_abbreviation' => 'MIS',
                    'name_en' => 'Gear nei',
                    'name_id' => 'Alat tangkap tidak terklasifikasi lainnya',
                    'category' => 'lainnya',
                    'level' => 2,
                    'parent_code' => '10.0',
                    'sort_order' => 119,
                ],

                // === 99 GEAR NOT KNOWN ===
                [
                    'isscfg_code' => '99.9',
                    'standard_abbreviation' => 'NK',
                    'name_en' => 'Gear not known',
                    'name_id' => 'Alat tangkap tidak diketahui',
                    'category' => 'lainnya',
                    'level' => 1,
                    'parent_code' => null,
                    'sort_order' => 120,
                ],
            ];

            // 2. INSERT/UPDATE FAO RECORDS SECARA HIERARKIS (LEVEL 1 -> LEVEL 2 -> LEVEL 3)
            $faoRecordsMap = [];

            // Seed Level 1
            foreach (array_filter($canonicalFaoGears, fn ($g) => $g['level'] === 1) as $g) {
                $fao = FishingGear::updateOrCreate(
                    ['source' => 'FAO_ISSCFG', 'isscfg_code' => $g['isscfg_code']],
                    [
                        'code' => 'FAO-'.$g['isscfg_code'],
                        'parent_id' => null,
                        'standard_abbreviation' => $g['standard_abbreviation'],
                        'name' => mb_strimwidth($g['name_en'].' ('.$g['name_id'].')', 0, 100, ''),
                        'name_en' => $g['name_en'],
                        'name_id' => $g['name_id'],
                        'local_name' => null,
                        'category' => $g['category'],
                        'level' => $g['level'],
                        'description' => 'Standar FAO/CWP ISSCFG Annex M: '.$g['name_en'],
                        'is_active' => true,
                        'sort_order' => $g['sort_order'],
                    ]
                );
                $faoRecordsMap[$g['isscfg_code']] = $fao->id;
            }

            // Seed Level 2
            foreach (array_filter($canonicalFaoGears, fn ($g) => $g['level'] === 2) as $g) {
                $parentId = isset($g['parent_code']) && isset($faoRecordsMap[$g['parent_code']])
                    ? $faoRecordsMap[$g['parent_code']]
                    : null;

                $fao = FishingGear::updateOrCreate(
                    ['source' => 'FAO_ISSCFG', 'isscfg_code' => $g['isscfg_code']],
                    [
                        'code' => 'FAO-'.$g['isscfg_code'],
                        'parent_id' => $parentId,
                        'standard_abbreviation' => $g['standard_abbreviation'],
                        'name' => mb_strimwidth($g['name_en'].' ('.$g['name_id'].')', 0, 100, ''),
                        'name_en' => $g['name_en'],
                        'name_id' => $g['name_id'],
                        'local_name' => null,
                        'category' => $g['category'],
                        'level' => $g['level'],
                        'description' => 'Standar FAO/CWP ISSCFG Annex M: '.$g['name_en'],
                        'is_active' => true,
                        'sort_order' => $g['sort_order'],
                    ]
                );
                $faoRecordsMap[$g['isscfg_code']] = $fao->id;
            }

            // Seed Level 3
            foreach (array_filter($canonicalFaoGears, fn ($g) => $g['level'] === 3) as $g) {
                $parentId = isset($g['parent_code']) && isset($faoRecordsMap[$g['parent_code']])
                    ? $faoRecordsMap[$g['parent_code']]
                    : null;

                $fao = FishingGear::updateOrCreate(
                    ['source' => 'FAO_ISSCFG', 'isscfg_code' => $g['isscfg_code']],
                    [
                        'code' => 'FAO-'.$g['isscfg_code'],
                        'parent_id' => $parentId,
                        'standard_abbreviation' => $g['standard_abbreviation'],
                        'name' => mb_strimwidth($g['name_en'].' ('.$g['name_id'].')', 0, 100, ''),
                        'name_en' => $g['name_en'],
                        'name_id' => $g['name_id'],
                        'local_name' => null,
                        'category' => $g['category'],
                        'level' => $g['level'],
                        'description' => 'Standar FAO/CWP ISSCFG Annex M: '.$g['name_en'],
                        'is_active' => true,
                        'sort_order' => $g['sort_order'],
                    ]
                );
                $faoRecordsMap[$g['isscfg_code']] = $fao->id;
            }

            // 3. MAPPING 12 DATA OPERASIONAL LOKAL ACEH (ID 1–12 DIJAGA MUTLAK)
            $localMappings = [
                1 => [
                    'code' => 'PS-01',
                    'isscfg_code' => '01.1',
                    'standard_abbreviation' => 'PS',
                    'name_en' => 'Purse seines',
                    'name_id' => 'Pukat Cincin Satu Kapal',
                    'local_name' => 'Pukat Cincin Teri',
                    'level' => 4,
                    'source' => 'LOCAL',
                    'sort_order' => 1,
                ],
                2 => [
                    'code' => 'PS-02',
                    'isscfg_code' => '01.1',
                    'standard_abbreviation' => 'PS',
                    'name_en' => 'Purse seines',
                    'name_id' => 'Pukat Cincin Mini',
                    'local_name' => 'Pukat Cincin Pelagis',
                    'level' => 4,
                    'source' => 'LOCAL',
                    'sort_order' => 2,
                ],
                3 => [
                    'code' => 'LL-01',
                    'isscfg_code' => '09.32',
                    'standard_abbreviation' => 'LLD',
                    'name_en' => 'Drifting longlines',
                    'name_id' => 'Rawai Hanyut Tuna',
                    'local_name' => 'Rawai Tuna',
                    'level' => 4,
                    'source' => 'LOCAL',
                    'sort_order' => 3,
                ],
                4 => [
                    'code' => 'LL-02',
                    'isscfg_code' => '09.31',
                    'standard_abbreviation' => 'LLS',
                    'name_en' => 'Set longlines',
                    'name_id' => 'Rawai Dasar',
                    'local_name' => 'Rawai Dasar',
                    'level' => 4,
                    'source' => 'LOCAL',
                    'sort_order' => 4,
                ],
                5 => [
                    'code' => 'HL-01',
                    'isscfg_code' => '09.1',
                    'standard_abbreviation' => 'LHP',
                    'name_en' => 'Handlines and hand-operated pole-and-lines',
                    'name_id' => 'Pancing Ulur',
                    'local_name' => 'Pancing Ulur',
                    'level' => 4,
                    'source' => 'LOCAL',
                    'sort_order' => 5,
                ],
                6 => [
                    'code' => 'TL-01',
                    'isscfg_code' => '09.5',
                    'standard_abbreviation' => 'LTL',
                    'name_en' => 'Trolling lines',
                    'name_id' => 'Pancing Tonda',
                    'local_name' => 'Pancing Tonda',
                    'level' => 4,
                    'source' => 'LOCAL',
                    'sort_order' => 6,
                ],
                7 => [
                    'code' => 'GN-01',
                    'isscfg_code' => '07.2',
                    'standard_abbreviation' => 'GND',
                    'name_en' => 'Drift gillnets',
                    'name_id' => 'Jaring Insang Hanyut',
                    'local_name' => 'Jaring Insang Hanyut',
                    'level' => 4,
                    'source' => 'LOCAL',
                    'sort_order' => 7,
                ],
                8 => [
                    'code' => 'GN-02',
                    'isscfg_code' => '07.1',
                    'standard_abbreviation' => 'GNS',
                    'name_en' => 'Set gillnets (anchored)',
                    'name_id' => 'Jaring Insang Tetap',
                    'local_name' => 'Jaring Insang Tetap',
                    'level' => 4,
                    'source' => 'LOCAL',
                    'sort_order' => 8,
                ],
                9 => [
                    'code' => 'TN-01',
                    'isscfg_code' => '07.5',
                    'standard_abbreviation' => 'GTR',
                    'name_en' => 'Trammel nets',
                    'name_id' => 'Jaring Tiga Lapis (Trammel Net)',
                    'local_name' => 'Jaring Gondrong (Trammel Net)',
                    'level' => 4,
                    'source' => 'LOCAL',
                    'sort_order' => 9,
                ],
                10 => [
                    'code' => 'BS-01',
                    'isscfg_code' => '02.1',
                    'standard_abbreviation' => 'SB',
                    'name_en' => 'Beach seines',
                    'name_id' => 'Pukat Pantai',
                    'local_name' => 'Pukat Pantai',
                    'level' => 4,
                    'source' => 'LOCAL',
                    'sort_order' => 10,
                ],
                11 => [
                    'code' => 'TR-01',
                    'isscfg_code' => '08.2',
                    'standard_abbreviation' => 'FPO',
                    'name_en' => 'Pots',
                    'name_id' => 'Bubu Perangkap Dasar',
                    'local_name' => 'Bubu Laut',
                    'level' => 4,
                    'source' => 'LOCAL',
                    'sort_order' => 11,
                ],
                12 => [
                    'code' => 'LN-01',
                    'isscfg_code' => '05.2',
                    'standard_abbreviation' => 'LNB',
                    'name_en' => 'Boat-operated lift nets',
                    'name_id' => 'Bagan Perahu Berlampu',
                    'local_name' => 'Bagan Perahu',
                    'level' => 4,
                    'source' => 'LOCAL',
                    'sort_order' => 12,
                ],
            ];

            foreach ($localMappings as $id => $data) {
                $parentId = isset($faoRecordsMap[$data['isscfg_code']])
                    ? $faoRecordsMap[$data['isscfg_code']]
                    : null;

                FishingGear::where('id', $id)->update([
                    'parent_id' => $parentId,
                    'isscfg_code' => $data['isscfg_code'],
                    'standard_abbreviation' => $data['standard_abbreviation'],
                    'name_en' => $data['name_en'],
                    'name_id' => $data['name_id'],
                    'local_name' => $data['local_name'],
                    'level' => $data['level'],
                    'source' => $data['source'],
                    'sort_order' => $data['sort_order'],
                ]);
            }
        });
    }
}
