<?php

namespace Database\Seeders;

use App\Models\FishingGear;
use Illuminate\Database\Seeder;

class FishingGearIsscfgSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Standar FAO/CWP Annex M (ISSCFG 2016 / CWP-25) & Mapping 12 Data Lokal Aceh.
     * IDEMPOTENT: Aman dijalankan berulang tanpa merusak/menduplikasi data.
     */
    public function run(): void
    {
        // -------------------------------------------------------------
        // 1. DAFTAR STANDAR FAO/CWP ISSCFG (ANNEX M)
        // -------------------------------------------------------------
        $faoGears = [
            // 01.0 SURROUNDING NETS
            [
                'isscfg_code' => '01.0',
                'standard_abbreviation' => null,
                'name_en' => 'Surrounding nets',
                'name_id' => 'Jaring Lingkar',
                'category' => 'jaring_lingkar',
                'level' => 1,
                'parent_code' => null,
                'sort_order' => 10,
            ],
            [
                'isscfg_code' => '01.1',
                'standard_abbreviation' => 'PS',
                'name_en' => 'Purse seines',
                'name_id' => 'Pukat Cincin',
                'category' => 'jaring_lingkar',
                'level' => 2,
                'parent_code' => '01.0',
                'sort_order' => 11,
            ],
            [
                'isscfg_code' => '01.2',
                'standard_abbreviation' => 'LA',
                'name_en' => 'Surrounding nets without purse lines',
                'name_id' => 'Jaring Lingkar Tanpa Tali Kerut (Lampara)',
                'category' => 'jaring_lingkar',
                'level' => 2,
                'parent_code' => '01.0',
                'sort_order' => 12,
            ],

            // 02.0 SEINE NETS
            [
                'isscfg_code' => '02.0',
                'standard_abbreviation' => null,
                'name_en' => 'Seine nets',
                'name_id' => 'Pukat Tarik / Seine Net',
                'category' => 'jaring_tarik',
                'level' => 1,
                'parent_code' => null,
                'sort_order' => 20,
            ],
            [
                'isscfg_code' => '02.1',
                'standard_abbreviation' => 'SB',
                'name_en' => 'Beach seines',
                'name_id' => 'Pukat Pantai',
                'category' => 'jaring_tarik',
                'level' => 2,
                'parent_code' => '02.0',
                'sort_order' => 21,
            ],
            [
                'isscfg_code' => '02.2',
                'standard_abbreviation' => 'SV',
                'name_en' => 'Boat seines',
                'name_id' => 'Pukat Tarik Berkapal',
                'category' => 'jaring_tarik',
                'level' => 2,
                'parent_code' => '02.0',
                'sort_order' => 22,
            ],
            [
                'isscfg_code' => '02.21',
                'standard_abbreviation' => 'SDN',
                'name_en' => 'Danish seines',
                'name_id' => 'Danish Seines',
                'category' => 'jaring_tarik',
                'level' => 3,
                'parent_code' => '02.2',
                'sort_order' => 23,
            ],
            [
                'isscfg_code' => '02.22',
                'standard_abbreviation' => 'SSC',
                'name_en' => 'Scottish seines',
                'name_id' => 'Scottish Seines',
                'category' => 'jaring_tarik',
                'level' => 3,
                'parent_code' => '02.2',
                'sort_order' => 24,
            ],
            [
                'isscfg_code' => '02.23',
                'standard_abbreviation' => 'SPR',
                'name_en' => 'Pair seines',
                'name_id' => 'Pair Seines',
                'category' => 'jaring_tarik',
                'level' => 3,
                'parent_code' => '02.2',
                'sort_order' => 25,
            ],

            // 03.0 TRAWLS
            [
                'isscfg_code' => '03.0',
                'standard_abbreviation' => null,
                'name_en' => 'Trawls',
                'name_id' => 'Pukat Hela (Trawl)',
                'category' => 'jaring_hela',
                'level' => 1,
                'parent_code' => null,
                'sort_order' => 30,
            ],
            [
                'isscfg_code' => '03.1',
                'standard_abbreviation' => null,
                'name_en' => 'Bottom trawls',
                'name_id' => 'Pukat Hela Dasar',
                'category' => 'jaring_hela',
                'level' => 2,
                'parent_code' => '03.0',
                'sort_order' => 31,
            ],
            [
                'isscfg_code' => '03.11',
                'standard_abbreviation' => 'TBB',
                'name_en' => 'Beam trawls',
                'name_id' => 'Beam Trawls',
                'category' => 'jaring_hela',
                'level' => 3,
                'parent_code' => '03.1',
                'sort_order' => 32,
            ],
            [
                'isscfg_code' => '03.12',
                'standard_abbreviation' => 'OTB',
                'name_en' => 'Single boat bottom otter trawls',
                'name_id' => 'Pukat Hela Dasar Berpapan Tunggal',
                'category' => 'jaring_hela',
                'level' => 3,
                'parent_code' => '03.1',
                'sort_order' => 33,
            ],
            [
                'isscfg_code' => '03.13',
                'standard_abbreviation' => 'OTT',
                'name_en' => 'Twin bottom otter trawls',
                'name_id' => 'Pukat Hela Dasar Berpapan Ganda',
                'category' => 'jaring_hela',
                'level' => 3,
                'parent_code' => '03.1',
                'sort_order' => 34,
            ],
            [
                'isscfg_code' => '03.14',
                'standard_abbreviation' => 'PTB',
                'name_en' => 'Bottom pair trawls',
                'name_id' => 'Pukat Hela Dasar Ganda (Dua Kapal)',
                'category' => 'jaring_hela',
                'level' => 3,
                'parent_code' => '03.1',
                'sort_order' => 35,
            ],
            [
                'isscfg_code' => '03.15',
                'standard_abbreviation' => 'TB',
                'name_en' => 'Other bottom trawls',
                'name_id' => 'Pukat Hela Dasar Lainnya',
                'category' => 'jaring_hela',
                'level' => 3,
                'parent_code' => '03.1',
                'sort_order' => 36,
            ],
            [
                'isscfg_code' => '03.2',
                'standard_abbreviation' => null,
                'name_en' => 'Midwater trawls',
                'name_id' => 'Pukat Hela Pertengahan',
                'category' => 'jaring_hela',
                'level' => 2,
                'parent_code' => '03.0',
                'sort_order' => 37,
            ],
            [
                'isscfg_code' => '03.21',
                'standard_abbreviation' => 'OTM',
                'name_en' => 'Single boat midwater otter trawls',
                'name_id' => 'Pukat Hela Pertengahan Berpapan Tunggal',
                'category' => 'jaring_hela',
                'level' => 3,
                'parent_code' => '03.2',
                'sort_order' => 38,
            ],
            [
                'isscfg_code' => '03.22',
                'standard_abbreviation' => 'PTM',
                'name_en' => 'Midwater pair trawls',
                'name_id' => 'Pukat Hela Pertengahan Dua Kapal',
                'category' => 'jaring_hela',
                'level' => 3,
                'parent_code' => '03.2',
                'sort_order' => 39,
            ],

            // 04.0 DREDGES
            [
                'isscfg_code' => '04.0',
                'standard_abbreviation' => null,
                'name_en' => 'Dredges',
                'name_id' => 'Penggaruk (Dredge)',
                'category' => 'lainnya',
                'level' => 1,
                'parent_code' => null,
                'sort_order' => 40,
            ],
            [
                'isscfg_code' => '04.1',
                'standard_abbreviation' => 'DRB',
                'name_en' => 'Towed dredges',
                'name_id' => 'Penggaruk Tarik Kapal',
                'category' => 'lainnya',
                'level' => 2,
                'parent_code' => '04.0',
                'sort_order' => 41,
            ],
            [
                'isscfg_code' => '04.2',
                'standard_abbreviation' => 'DRH',
                'name_en' => 'Hand dredges',
                'name_id' => 'Penggaruk Tangan',
                'category' => 'lainnya',
                'level' => 2,
                'parent_code' => '04.0',
                'sort_order' => 42,
            ],

            // 05.0 LIFT NETS
            [
                'isscfg_code' => '05.0',
                'standard_abbreviation' => null,
                'name_en' => 'Lift nets',
                'name_id' => 'Jaring Angkat',
                'category' => 'jaring_angkat',
                'level' => 1,
                'parent_code' => null,
                'sort_order' => 50,
            ],
            [
                'isscfg_code' => '05.1',
                'standard_abbreviation' => 'LNP',
                'name_en' => 'Portable lift nets',
                'name_id' => 'Jaring Angkat Portabel / Tangan (Anco)',
                'category' => 'jaring_angkat',
                'level' => 2,
                'parent_code' => '05.0',
                'sort_order' => 51,
            ],
            [
                'isscfg_code' => '05.2',
                'standard_abbreviation' => 'LNB',
                'name_en' => 'Boat-operated lift nets',
                'name_id' => 'Jaring Angkat Berkapal (Bagan Perahu)',
                'category' => 'jaring_angkat',
                'level' => 2,
                'parent_code' => '05.0',
                'sort_order' => 52,
            ],
            [
                'isscfg_code' => '05.3',
                'standard_abbreviation' => 'LNS',
                'name_en' => 'Shore-operated stationary lift nets',
                'name_id' => 'Jaring Angkat Menetap di Pantai (Bagan Tancap)',
                'category' => 'jaring_angkat',
                'level' => 2,
                'parent_code' => '05.0',
                'sort_order' => 53,
            ],
            [
                'isscfg_code' => '05.9',
                'standard_abbreviation' => 'LN',
                'name_en' => 'Other lift nets',
                'name_id' => 'Jaring Angkat Lainnya',
                'category' => 'jaring_angkat',
                'level' => 2,
                'parent_code' => '05.0',
                'sort_order' => 54,
            ],

            // 06.0 FALLING GEAR
            [
                'isscfg_code' => '06.0',
                'standard_abbreviation' => null,
                'name_en' => 'Falling gear',
                'name_id' => 'Alat yang Dijatuhkan',
                'category' => 'alat_jatuh',
                'level' => 1,
                'parent_code' => null,
                'sort_order' => 60,
            ],
            [
                'isscfg_code' => '06.1',
                'standard_abbreviation' => 'FCN',
                'name_en' => 'Cast nets',
                'name_id' => 'Jala Lempar (Cast Net)',
                'category' => 'alat_jatuh',
                'level' => 2,
                'parent_code' => '06.0',
                'sort_order' => 61,
            ],
            [
                'isscfg_code' => '06.2',
                'standard_abbreviation' => 'FCO',
                'name_en' => 'Cover pots',
                'name_id' => 'Perangkap Jatuh / Tudung',
                'category' => 'alat_jatuh',
                'level' => 2,
                'parent_code' => '06.0',
                'sort_order' => 62,
            ],

            // 07.0 GILLNETS AND ENTANGLING NETS
            [
                'isscfg_code' => '07.0',
                'standard_abbreviation' => null,
                'name_en' => 'Gillnets and entangling nets',
                'name_id' => 'Jaring Insang dan Jaring Belit',
                'category' => 'jaring_insang',
                'level' => 1,
                'parent_code' => null,
                'sort_order' => 70,
            ],
            [
                'isscfg_code' => '07.1',
                'standard_abbreviation' => 'GNS',
                'name_en' => 'Set gillnets (anchored)',
                'name_id' => 'Jaring Insang Tetap (Dasar)',
                'category' => 'jaring_insang',
                'level' => 2,
                'parent_code' => '07.0',
                'sort_order' => 71,
            ],
            [
                'isscfg_code' => '07.2',
                'standard_abbreviation' => 'GND',
                'name_en' => 'Driftnets',
                'name_id' => 'Jaring Insang Hanyut',
                'category' => 'jaring_insang',
                'level' => 2,
                'parent_code' => '07.0',
                'sort_order' => 72,
            ],
            [
                'isscfg_code' => '07.3',
                'standard_abbreviation' => 'GNC',
                'name_en' => 'Encircling gillnets',
                'name_id' => 'Jaring Insang Lingkar',
                'category' => 'jaring_insang',
                'level' => 2,
                'parent_code' => '07.0',
                'sort_order' => 73,
            ],
            [
                'isscfg_code' => '07.4',
                'standard_abbreviation' => 'GNF',
                'name_en' => 'Fixed gillnets (on stakes)',
                'name_id' => 'Jaring Insang Pancang',
                'category' => 'jaring_insang',
                'level' => 2,
                'parent_code' => '07.0',
                'sort_order' => 74,
            ],
            [
                'isscfg_code' => '07.5',
                'standard_abbreviation' => 'GTR',
                'name_en' => 'Trammel nets',
                'name_id' => 'Jaring Tiga Lapis (Trammel Net)',
                'category' => 'jaring_insang',
                'level' => 2,
                'parent_code' => '07.0',
                'sort_order' => 75,
            ],
            [
                'isscfg_code' => '07.6',
                'standard_abbreviation' => 'GTN',
                'name_en' => 'Combined gillnets-trammel nets',
                'name_id' => 'Jaring Insang-Trammel Kombinasi',
                'category' => 'jaring_insang',
                'level' => 2,
                'parent_code' => '07.0',
                'sort_order' => 76,
            ],

            // 08.0 TRAPS
            [
                'isscfg_code' => '08.0',
                'standard_abbreviation' => null,
                'name_en' => 'Traps',
                'name_id' => 'Perangkap',
                'category' => 'perangkap',
                'level' => 1,
                'parent_code' => null,
                'sort_order' => 80,
            ],
            [
                'isscfg_code' => '08.1',
                'standard_abbreviation' => 'FPN',
                'name_en' => 'Stationary uncovered pound nets',
                'name_id' => 'Perangkap Pasang Surut / Sero',
                'category' => 'perangkap',
                'level' => 2,
                'parent_code' => '08.0',
                'sort_order' => 81,
            ],
            [
                'isscfg_code' => '08.2',
                'standard_abbreviation' => 'FPO',
                'name_en' => 'Pots',
                'name_id' => 'Bubu (Pots / Traps)',
                'category' => 'perangkap',
                'level' => 2,
                'parent_code' => '08.0',
                'sort_order' => 82,
            ],
            [
                'isscfg_code' => '08.3',
                'standard_abbreviation' => 'FYK',
                'name_en' => 'Fyke nets',
                'name_id' => 'Perangkap Corong (Fyke Net)',
                'category' => 'perangkap',
                'level' => 2,
                'parent_code' => '08.0',
                'sort_order' => 83,
            ],
            [
                'isscfg_code' => '08.4',
                'standard_abbreviation' => 'FSN',
                'name_en' => 'Stow nets',
                'name_id' => 'Jaring Kantong Pasang Surut',
                'category' => 'perangkap',
                'level' => 2,
                'parent_code' => '08.0',
                'sort_order' => 84,
            ],
            [
                'isscfg_code' => '08.5',
                'standard_abbreviation' => 'FWR',
                'name_en' => 'Barriers, fences, weirs',
                'name_id' => 'Pagar Rintangan / Belat',
                'category' => 'perangkap',
                'level' => 2,
                'parent_code' => '08.0',
                'sort_order' => 85,
            ],
            [
                'isscfg_code' => '08.6',
                'standard_abbreviation' => 'FAR',
                'name_en' => 'Aerial traps',
                'name_id' => 'Perangkap Udara (Ikan Terbang)',
                'category' => 'perangkap',
                'level' => 2,
                'parent_code' => '08.0',
                'sort_order' => 86,
            ],
            [
                'isscfg_code' => '08.9',
                'standard_abbreviation' => 'FIX',
                'name_en' => 'Other traps',
                'name_id' => 'Perangkap Lainnya',
                'category' => 'perangkap',
                'level' => 2,
                'parent_code' => '08.0',
                'sort_order' => 87,
            ],

            // 09.0 HOOKS AND LINES (ANNEX M 2016)
            [
                'isscfg_code' => '09.0',
                'standard_abbreviation' => null,
                'name_en' => 'Hooks and lines',
                'name_id' => 'Pancing (Hook and Line)',
                'category' => 'pancing',
                'level' => 1,
                'parent_code' => null,
                'sort_order' => 90,
            ],
            [
                'isscfg_code' => '09.1',
                'standard_abbreviation' => 'LHP',
                'name_en' => 'Handlines and hand-operated pole-and-lines',
                'name_id' => 'Pancing Ulur Tradisional',
                'category' => 'pancing',
                'level' => 2,
                'parent_code' => '09.0',
                'sort_order' => 91,
            ],
            [
                'isscfg_code' => '09.2',
                'standard_abbreviation' => 'LHM',
                'name_en' => 'Mechanized lines and pole-and-lines',
                'name_id' => 'Pancing Mekanis / Pole and Line',
                'category' => 'pancing',
                'level' => 2,
                'parent_code' => '09.0',
                'sort_order' => 92,
            ],
            [
                'isscfg_code' => '09.3',
                'standard_abbreviation' => null,
                'name_en' => 'Longlines',
                'name_id' => 'Pancing Rawai (Longline)',
                'category' => 'pancing',
                'level' => 2,
                'parent_code' => '09.0',
                'sort_order' => 93,
            ],
            [
                'isscfg_code' => '09.31',
                'standard_abbreviation' => 'LLS',
                'name_en' => 'Set longlines',
                'name_id' => 'Rawai Tetap Dasar (Bottom Longline)',
                'category' => 'pancing',
                'level' => 3,
                'parent_code' => '09.3',
                'sort_order' => 94,
            ],
            [
                'isscfg_code' => '09.32',
                'standard_abbreviation' => 'LLD',
                'name_en' => 'Drifting longlines',
                'name_id' => 'Rawai Hanyut (Drift Longline / Tuna Longline)',
                'category' => 'pancing',
                'level' => 3,
                'parent_code' => '09.3',
                'sort_order' => 95,
            ],
            [
                'isscfg_code' => '09.4',
                'standard_abbreviation' => 'LVT',
                'name_en' => 'Vertical lines',
                'name_id' => 'Pancing Vertikal (Drop Line)',
                'category' => 'pancing',
                'level' => 2,
                'parent_code' => '09.0',
                'sort_order' => 96,
            ],
            [
                'isscfg_code' => '09.5',
                'standard_abbreviation' => 'LTL',
                'name_en' => 'Trolling lines',
                'name_id' => 'Pancing Tonda (Troll Line)',
                'category' => 'pancing',
                'level' => 2,
                'parent_code' => '09.0',
                'sort_order' => 97,
            ],
            [
                'isscfg_code' => '09.9',
                'standard_abbreviation' => 'LX',
                'name_en' => 'Other hooks and lines',
                'name_id' => 'Pancing Lainnya',
                'category' => 'pancing',
                'level' => 2,
                'parent_code' => '09.0',
                'sort_order' => 98,
            ],

            // 10.0 MISCELLANEOUS GEAR
            [
                'isscfg_code' => '10.0',
                'standard_abbreviation' => null,
                'name_en' => 'Miscellaneous gear',
                'name_id' => 'Alat Penjepit, Melukai & Lainnya',
                'category' => 'alat_penjepit_melukai',
                'level' => 1,
                'parent_code' => null,
                'sort_order' => 100,
            ],
            [
                'isscfg_code' => '10.1',
                'standard_abbreviation' => 'HAR',
                'name_en' => 'Harpoons',
                'name_id' => 'Harpon (Panah Laut)',
                'category' => 'alat_penjepit_melukai',
                'level' => 2,
                'parent_code' => '10.0',
                'sort_order' => 101,
            ],
            [
                'isscfg_code' => '10.9',
                'standard_abbreviation' => 'MIS',
                'name_en' => 'Other gear',
                'name_id' => 'Alat Tangkap Lainnya',
                'category' => 'lainnya',
                'level' => 2,
                'parent_code' => '10.0',
                'sort_order' => 102,
            ],

            // 20.0 GEAR NOT KNOWN
            [
                'isscfg_code' => '20.0',
                'standard_abbreviation' => 'NK',
                'name_en' => 'Gear not known or not specified',
                'name_id' => 'Alat Tangkap Tidak Diketahui / Tidak Spesifik',
                'category' => 'lainnya',
                'level' => 1,
                'parent_code' => null,
                'sort_order' => 200,
            ],
        ];

        // -------------------------------------------------------------
        // 2. SEED DATA STANDAR FAO SECARA HIERARKIS (IDEMPOTENT)
        // -------------------------------------------------------------
        $faoRecordsMap = [];

        // Seed Level 1 terlebih dahulu
        foreach (array_filter($faoGears, fn ($g) => $g['level'] === 1) as $g) {
            $fao = FishingGear::updateOrCreate(
                ['code' => 'FAO-'.$g['isscfg_code']],
                [
                    'isscfg_code' => $g['isscfg_code'],
                    'standard_abbreviation' => $g['standard_abbreviation'],
                    'name' => $g['name_en'].' ('.$g['name_id'].')',
                    'name_en' => $g['name_en'],
                    'name_id' => $g['name_id'],
                    'local_name' => null,
                    'category' => $g['category'],
                    'level' => $g['level'],
                    'source' => 'FAO_ISSCFG',
                    'description' => 'Standar FAO/CWP ISSCFG Annex M: '.$g['name_en'],
                    'is_active' => true,
                    'sort_order' => $g['sort_order'],
                    'parent_id' => null,
                ]
            );
            $faoRecordsMap[$g['isscfg_code']] = $fao->id;
        }

        // Seed Level 2
        foreach (array_filter($faoGears, fn ($g) => $g['level'] === 2) as $g) {
            $parentId = isset($g['parent_code']) && isset($faoRecordsMap[$g['parent_code']])
                ? $faoRecordsMap[$g['parent_code']]
                : null;

            $fao = FishingGear::updateOrCreate(
                ['code' => 'FAO-'.$g['isscfg_code']],
                [
                    'parent_id' => $parentId,
                    'isscfg_code' => $g['isscfg_code'],
                    'standard_abbreviation' => $g['standard_abbreviation'],
                    'name' => $g['name_en'].' ('.$g['name_id'].')',
                    'name_en' => $g['name_en'],
                    'name_id' => $g['name_id'],
                    'local_name' => null,
                    'category' => $g['category'],
                    'level' => $g['level'],
                    'source' => 'FAO_ISSCFG',
                    'description' => 'Standar FAO/CWP ISSCFG Annex M: '.$g['name_en'],
                    'is_active' => true,
                    'sort_order' => $g['sort_order'],
                ]
            );
            $faoRecordsMap[$g['isscfg_code']] = $fao->id;
        }

        // Seed Level 3
        foreach (array_filter($faoGears, fn ($g) => $g['level'] === 3) as $g) {
            $parentId = isset($g['parent_code']) && isset($faoRecordsMap[$g['parent_code']])
                ? $faoRecordsMap[$g['parent_code']]
                : null;

            $fao = FishingGear::updateOrCreate(
                ['code' => 'FAO-'.$g['isscfg_code']],
                [
                    'parent_id' => $parentId,
                    'isscfg_code' => $g['isscfg_code'],
                    'standard_abbreviation' => $g['standard_abbreviation'],
                    'name' => $g['name_en'].' ('.$g['name_id'].')',
                    'name_en' => $g['name_en'],
                    'name_id' => $g['name_id'],
                    'local_name' => null,
                    'category' => $g['category'],
                    'level' => $g['level'],
                    'source' => 'FAO_ISSCFG',
                    'description' => 'Standar FAO/CWP ISSCFG Annex M: '.$g['name_en'],
                    'is_active' => true,
                    'sort_order' => $g['sort_order'],
                ]
            );
            $faoRecordsMap[$g['isscfg_code']] = $fao->id;
        }

        // -------------------------------------------------------------
        // 3. MAPPING 12 DATA OPERASIONAL LOKAL ACEH (ID 1–12 DIJAGA)
        // -------------------------------------------------------------
        $localMappings = [
            1 => [
                'code' => 'PS-01',
                'isscfg_code' => '01.1',
                'standard_abbreviation' => 'PS',
                'name_en' => 'Purse seines',
                'name_id' => 'Pukat Cincin Satu Kapal',
                'local_name' => 'Pukat Langgar',
                'level' => 4,
                'source' => 'LOCAL',
                'sort_order' => 1,
            ],
            2 => [
                'code' => 'PS-02',
                'isscfg_code' => '01.1',
                'standard_abbreviation' => 'PS',
                'name_en' => 'Purse seines',
                'name_id' => 'Pukat Cincin Mini',
                'local_name' => 'Pukat Cincin Mini Pesisir',
                'level' => 4,
                'source' => 'LOCAL',
                'sort_order' => 2,
            ],
            3 => [
                'code' => 'LL-01',
                'isscfg_code' => '09.32',
                'standard_abbreviation' => 'LLD',
                'name_en' => 'Drifting longlines',
                'name_id' => 'Rawai Hanyut Tuna',
                'local_name' => 'Rawai Tuna Samudera',
                'level' => 4,
                'source' => 'LOCAL',
                'sort_order' => 3,
            ],
            4 => [
                'code' => 'LL-02',
                'isscfg_code' => '09.31',
                'standard_abbreviation' => 'LLS',
                'name_en' => 'Set longlines',
                'name_id' => 'Rawai Dasar',
                'local_name' => 'Rawai Karang',
                'level' => 4,
                'source' => 'LOCAL',
                'sort_order' => 4,
            ],
            5 => [
                'code' => 'HL-01',
                'isscfg_code' => '09.1',
                'standard_abbreviation' => 'LHP',
                'name_en' => 'Handlines and hand-operated pole-and-lines',
                'name_id' => 'Pancing Ulur',
                'local_name' => 'Pancing Ulur Tradisional',
                'level' => 4,
                'source' => 'LOCAL',
                'sort_order' => 5,
            ],
            6 => [
                'code' => 'TL-01',
                'isscfg_code' => '09.5',
                'standard_abbreviation' => 'LTL',
                'name_en' => 'Trolling lines',
                'name_id' => 'Pancing Tonda',
                'local_name' => 'Pancing Tonda',
                'level' => 4,
                'source' => 'LOCAL',
                'sort_order' => 6,
            ],
            7 => [
                'code' => 'GN-01',
                'isscfg_code' => '07.2',
                'standard_abbreviation' => 'GND',
                'name_en' => 'Driftnets',
                'name_id' => 'Jaring Insang Hanyut',
                'local_name' => 'Jaring Hanyut',
                'level' => 4,
                'source' => 'LOCAL',
                'sort_order' => 7,
            ],
            8 => [
                'code' => 'GN-02',
                'isscfg_code' => '07.1',
                'standard_abbreviation' => 'GNS',
                'name_en' => 'Set gillnets (anchored)',
                'name_id' => 'Jaring Insang Tetap Dasar',
                'local_name' => 'Jaring Dasar',
                'level' => 4,
                'source' => 'LOCAL',
                'sort_order' => 8,
            ],
            9 => [
                'code' => 'TN-01',
                'isscfg_code' => '07.5',
                'standard_abbreviation' => 'GTR',
                'name_en' => 'Trammel nets',
                'name_id' => 'Jaring Tiga Lapis (Trammel Net)',
                'local_name' => 'Jaring Klitik Udang',
                'level' => 4,
                'source' => 'LOCAL',
                'sort_order' => 9,
            ],
            10 => [
                'code' => 'BS-01',
                'isscfg_code' => '02.1',
                'standard_abbreviation' => 'SB',
                'name_en' => 'Beach seines',
                'name_id' => 'Pukat Pantai',
                'local_name' => 'Pukat Darat Aceh',
                'level' => 4,
                'source' => 'LOCAL',
                'sort_order' => 10,
            ],
            11 => [
                'code' => 'TR-01',
                'isscfg_code' => '08.2',
                'standard_abbreviation' => 'FPO',
                'name_en' => 'Pots',
                'name_id' => 'Bubu Perangkap Dasar',
                'local_name' => 'Bubu Karang',
                'level' => 4,
                'source' => 'LOCAL',
                'sort_order' => 11,
            ],
            12 => [
                'code' => 'LN-01',
                'isscfg_code' => '05.2',
                'standard_abbreviation' => 'LNB',
                'name_en' => 'Boat-operated lift nets',
                'name_id' => 'Bagan Perahu Berlampu',
                'local_name' => 'Bagan Perahu',
                'level' => 4,
                'source' => 'LOCAL',
                'sort_order' => 12,
            ],
        ];

        foreach ($localMappings as $id => $data) {
            $parentId = isset($faoRecordsMap[$data['isscfg_code']])
                ? $faoRecordsMap[$data['isscfg_code']]
                : null;

            FishingGear::where('id', $id)->update([
                'parent_id' => $parentId,
                'isscfg_code' => $data['isscfg_code'],
                'standard_abbreviation' => $data['standard_abbreviation'],
                'name_en' => $data['name_en'],
                'name_id' => $data['name_id'],
                'local_name' => $data['local_name'],
                'level' => $data['level'],
                'source' => $data['source'],
                'sort_order' => $data['sort_order'],
            ]);
        }
    }
}
